### ISSUE TITLE
Data datatype does not support time with timezone

### ISSUE THREAD

**Issue by coherit** [legiongis/arches#10]
See [arches/issues/6043](https://github.com/archesproject/arches/issues/6043)

When using a date datatype, the Collector App passes an ISO 6801 datetime with timezone, which the datatype.py date validator is not prepared for and fails to sync the project.

**Comment by coherit** [comment]
The process_mobile_data function in datatypes.py seems to be the perfect place to sanitize the datetime that the collector is passing. 

I had put some logic in the validate function, but it only checks if data are valid -- it doesn't return a new value like process_mobile_data does. When I've tried adapting process_mobile_data to process both dates and files, I fail -- it doesn't even seem to run. So, I'm missing something still, likely to do with provisional data edits since [process_mobile_data only runs on provisional edits (I think).](https://github.com/legiongis/arches/blob/b8a72a75c194857b55f8f639866b8b88251e35c3/arches/app/models/mobile_survey.py#L253)

Here's some simple validating logic that can be rewritten to sanitize once we hit the right function...
                parsed = parse_datetime(value)
                parsed = parsed.replace(tzinfo=None)
                try:
                     if datetime.strptime(str(parsed), "%Y-%m-%d %H:%M:%S"):
                          valid = True
                except:
                     valid = False

**Comment by mradamcox** [comment]
@coherit is this now addressed in Arches master?

**Comment by mradamcox** [comment]
@coherit I think we can close this, right? I'd like to disable Issues in this repo actually, so I'll do that once you can confirm this info is at least stored somewhere else.

**Comment by coherit** [comment]
Yes, I believe this was addressed by a later version of Arches
